export interface CurriculumCourse {
  semester: string;
  code: string;
  title: string;
  credits: string;
  department: string;
  passRate: number;
  averageGradePoint: string;
  activeBacklogs: number;
}

const courseRows: [string, string, string, string, string][] = [
  ['I', 'AGR 101', 'Fundamentals of Agronomy and Agricultural Heritage', '1+1', 'Agronomy'],
  ['I', 'BIC 101', 'Fundamentals of Plant Biochemistry', '2+1', 'Plant Biochemistry'],
  ['I', 'SAC 101', 'Fundamentals of Soil Science', '2+1', 'Soil Science'],
  ['I', 'FOR 111', 'Introduction to Forestry', '2+1', 'Forestry'],
  ['I', 'ENG 101', 'Comprehension and Communication Skills in English', '1+1', 'Communication'],
  ['I', 'HOR 111', 'Fundamentals of Horticulture', '1+1', 'Horticulture'],
  ['I', 'MAT 111', 'Elementary Mathematics', '1+1', 'Mathematics'],
  ['I', 'PBG 101', 'Introduction to Agricultural Botany', '1+1', 'Genetics and Plant Breeding'],
  ['I', 'AEX 101', 'Rural Sociology and Educational Psychology', '2+0', 'Agricultural Extension'],
  ['I', 'TAM 101 / ENG 103', 'Development Education', '0+1', 'General Education'],
  ['I', 'NSS/NCC 101', 'NSS / NCC', '0+1*', 'General Education'],
  ['I', 'PED 101', 'Physical Education', '0+1*', 'General Education'],
  ['I', 'PED 102', 'Yoga for Human Excellence', '0+1*', 'General Education'],
  ['II', 'SWE 112', 'Soil and Water Conservation Engineering', '1+1', 'Agricultural Engineering'],
  ['II', 'CRP 101', 'Fundamentals of Crop Physiology', '2+1', 'Crop Physiology'],
  ['II', 'AEC 102', 'Fundamentals of Agricultural Economics', '1+1', 'Agricultural Economics'],
  ['II', 'AGM 101', 'Fundamentals of Microbiology', '1+1', 'Agricultural Microbiology'],
  ['II', 'AEX 102', 'Fundamentals of Agricultural Extension Education', '2+1', 'Agricultural Extension'],
  ['II', 'FSN 111', 'Principles of Food Science and Nutrition', '1+1', 'Food Science'],
  ['II', 'AGR 102', 'Introductory Agro-meteorology and Climate Change', '1+1', 'Agronomy'],
  ['II', 'HOR 112', 'Production Technology for Fruit and Plantation Crops', '1+1', 'Horticulture'],
  ['II', 'RSG 101', 'Geo-informatics for Precision Farming', '1+0', 'Agricultural Engineering'],
  ['II', 'NSS/NCC 101', 'NSS / NCC', '0+1*', 'General Education'],
  ['II', 'PED 101', 'Physical Education', '0+1*', 'General Education'],
  ['III', 'PAT 201', 'Fundamentals of Plant Pathology', '2+1', 'Plant Pathology'],
  ['III', 'AEN 201', 'Fundamentals of Entomology', '2+1', 'Entomology'],
  ['III', 'SST 201', 'Principles of Seed Technology', '2+1', 'Seed Science'],
  ['III', 'AGR 201', 'Crop Production Technology I (Kharif Crops)', '1+1', 'Agronomy'],
  ['III', 'HOR 211', 'Production Technology for Vegetables and Spices', '1+1', 'Horticulture'],
  ['III', 'ENS 201', 'Environmental Studies and Disaster Management', '2+1', 'Environmental Science'],
  ['III', 'AMP 201', 'Livestock and Poultry Management', '1+1', 'Animal Science'],
  ['III', 'AEC 201', 'Farm Management, Production and Resource Economics', '1+1', 'Agricultural Economics'],
  ['III', 'SAC 201', 'Soil Resource Inventory', '1+1', 'Soil Science'],
  ['III', 'FMP 211', 'Farm Machinery and Power', '1+1', 'Agricultural Engineering'],
  ['III', 'AGR 202', 'Study Tour', '0+1*', 'Agronomy'],
  ['III', 'NSS/NCC 101', 'NSS / NCC', '0+1*', 'General Education'],
  ['III', 'PED 101', 'Physical Education', '0+1*', 'General Education'],
  ['IV', 'PBG 201', 'Fundamentals of Genetics', '2+1', 'Genetics and Plant Breeding'],
  ['IV', 'AEX 201', 'Communication Skills and Personality Development', '1+1', 'Agricultural Extension'],
  ['IV', 'STA 211', 'Statistical Methods', '1+1', 'Statistics'],
  ['IV', 'PAT 201', 'Principles of Plant Disease Management', '1+1', 'Plant Pathology'],
  ['IV', 'AEN 202', 'Management of Beneficial and Harmful Insects', '2+1', 'Entomology'],
  ['IV', 'AGR 203', 'Crop Production Technology II (Rabi Crops)', '1+1', 'Agronomy'],
  ['IV', 'AGR 204', 'Farming Systems and Sustainable Agriculture', '1+1', 'Agronomy'],
  ['IV', 'SAC 202', 'Problematic Soils and Their Management', '2+0', 'Soil Science'],
  ['IV', 'HOR 212', 'Production Technology for Ornamental Crops, MAP and Landscaping', '1+1', 'Horticulture'],
  ['IV', 'ANM 201', 'Introductory Nematology', '0+1', 'Nematology'],
  ['IV', 'NST 201', 'Fundamentals and Applications of Nanotechnology', '1+0', 'Nanotechnology'],
  ['IV', 'ERG 211', 'Renewable Energy and Green Technology', '1+1', 'Renewable Energy'],
  ['IV', 'NSS/NCC 101', 'NSS / NCC', '0+1*', 'General Education'],
  ['IV', 'PED 101', 'Physical Education', '0+1*', 'General Education'],
  ['IV', 'PED 102', 'Yoga for Human Excellence', '0+1*', 'General Education'],
  ['V', 'PBG 301', 'Fundamentals of Plant Breeding', '2+1', 'Genetics and Plant Breeding'],
  ['V', 'AEC 301', 'Agricultural Marketing, Trade and Prices', '2+1', 'Agricultural Economics'],
  ['V', 'AGM 301', 'Agricultural Microbiology', '1+1', 'Agricultural Microbiology'],
  ['V', 'PAT 301', 'Diseases of Field and Horticultural Crops and Their Management I', '1+1', 'Plant Pathology'],
  ['V', 'ARM 301', 'Entrepreneurship Development and Business Management', '1+1', 'Agribusiness'],
  ['V', 'HOR 111', 'Practical Crop Production I (Kharif Crops)', '0+2', 'Agronomy'],
  ['V', 'HOR 301', 'Post-harvest Management and Value Addition of Fruits and Vegetables', '1+1', 'Horticulture'],
  ['V', 'SAC 301', 'Manures, Fertilizers and Soil Fertility Management', '2+1', 'Soil Science'],
  ['V', 'APE 311', 'Protected Cultivation and Secondary Agriculture', '1+1', 'Agricultural Engineering'],
  ['V', 'AGR 302', 'Rainfed Agriculture and Watershed Management', '1+1', 'Agronomy'],
  ['V', 'AEN 301', 'Pests of Field Crops and Stored Produce and Their Management', '1+1', 'Entomology'],
  ['V', 'NCC 101', 'NCC', '0+0', 'General Education'],
  ['VI', 'AEC 302', 'Agricultural Finance and Co-operation', '2+1', 'Agricultural Economics'],
  ['VI', 'PAT 302', 'Diseases of Field and Horticultural Crops and Their Management II', '2+1', 'Plant Pathology'],
  ['VI', 'COM 311', 'Agro Informatics', '1+1', 'Agricultural Informatics'],
  ['VI', 'ENS 301', 'Environmental Pollution and Management', '1+1', 'Environmental Science'],
  ['VI', 'AEN 301', 'Pests of Crops and Stored Grain and Their Management', '2+1', 'Entomology'],
  ['VI', 'AGR 303', 'Practical Crop Production II (Rabi Crops)', '0+2', 'Agronomy'],
  ['VI', 'AGR 304', 'Principles of Organic Farming', '1+1', 'Agronomy'],
  ['VI', 'ABT 301', 'Plant Biotechnology', '2+1', 'Biotechnology'],
  ['VI', 'PBG 302', 'Crop Improvement', '2+1', 'Genetics and Plant Breeding'],
  ['VI', 'OPT 301', 'Optional Course', '1+1', 'Elective'],
  ['VI', 'AEN 301', 'Pests of Field Crops and Stored Produce and Their Management', '1+1', 'Entomology'],
  ['VI', 'NCC 101', 'NCC', '0+0', 'General Education'],
  ['VII', 'AEX 401', 'Student READY Programme (Rural Agricultural Work Experience and Agro-industrial Attachment)', '0+20', 'Agricultural Extension'],
  ['VII', 'AGR 401', 'Project Report Preparation, Presentation and Evaluation', '0+1', 'Agronomy'],
  ['VII', 'AEX 402', 'All India Study Tour', '0+1*', 'Agricultural Extension'],
  ['VIII', 'AGM 451', 'Bio-inoculant Production Technology', '0+10', 'Agricultural Microbiology'],
  ['VIII', 'HOR 451', 'Hybrid Seed Production in Vegetable Crops', '0+10', 'Horticulture'],
  ['VIII', 'SAC 451', 'On-farm Advisory for Soil Health, Water Quality and Plant Nutrition', '0+10', 'Soil Science'],
  ['VIII', 'AEN 451', 'Commercial Beekeeping', '0+10', 'Entomology'],
  ['VIII', 'SER 451', 'Commercial Cocoon Production', '0+10', 'Sericulture'],
  ['VIII', 'ABT 451', 'Commercial Plant Tissue Culture', '0+10', 'Biotechnology'],
  ['VIII', 'HOR 452', 'Commercial Nursery Production of Horticultural Crops', '0+10', 'Horticulture'],
  ['VIII', 'HOR 453', 'Commercial Landscape Gardening', '0+10', 'Horticulture'],
  ['VIII', 'PAT 451', 'Commercial Production of Bio-control Agents', '0+10', 'Plant Pathology'],
  ['VIII', 'PAT 452', 'Commercial Mushroom Production', '0+10', 'Plant Pathology'],
  ['VIII', 'AMP 451', 'Commercial Broiler and Layer Production', '0+10', 'Animal Science'],
  ['VIII', 'SST 451', 'Commercial Seed Production', '0+10', 'Seed Science'],
  ['VIII', 'PBG 451', 'Hybrid Pearl Millet Seed Production', '0+10', 'Genetics and Plant Breeding'],
  ['VIII', 'PBG 452', 'Hybrid Rice Parental Line Seed Production', '0+10', 'Genetics and Plant Breeding'],
  ['VIII', 'ARM 451', 'Managerial Skills for Agribusiness', '0+10', 'Agribusiness'],
  ['VIII', 'AGR 451', 'Development of Integrated Farming System Model', '0+10', 'Agronomy'],
  ['VIII', 'HOR 454', 'Protected Cultivation of Vegetable Crops', '0+10', 'Horticulture'],
  ['VIII', 'ENS 451', 'Composting Technology', '0+10', 'Environmental Science'],
  ['VIII', 'AGR 452', 'Organic Agriculture', '0+10', 'Agronomy']
];

const semesterOrder = ['I', 'II', 'III', 'IV', 'V', 'VI', 'VII', 'VIII'];

export const curriculumSemesters = semesterOrder.map(semester => ({
  semester,
  courses: courseRows.filter(([courseSemester]) => courseSemester === semester).map(([, code, title, credits, department], index) => ({
    semester,
    code,
    title,
    credits,
    department,
    passRate: 78 + ((index * 7 + semesterOrder.indexOf(semester) * 3) % 20),
    averageGradePoint: (7.2 + ((index * 3 + semesterOrder.indexOf(semester)) % 19) / 10).toFixed(1),
    activeBacklogs: 2 + ((index * 5 + semesterOrder.indexOf(semester) * 2) % 36)
  }))
}));

