import { Student, StudentProfile } from './types';

export const getStudentProfile = (student: Student): StudentProfile => ({
  student,
  registrationNumber: student.rollNo,
  nationality: 'Indian',
  religion: 'Not provided',
  community: student.category,
  caste: 'Not provided',
  motherTongue: 'Tamil',
  communicationAddress: `${student.district}, ${student.state}`,
  permanentAddress: `${student.district}, ${student.state}`,
  pinCode: '641001',
  whatsappNumber: student.phone,
  admissionType: 'Regular',
  admissionQuota: student.quota,
  firstGraduate: student.firstGenerationGraduate ? 'Yes' : 'No',
  tenthBoard: 'State Board',
  tenthSchool: student.schoolType,
  tenthPassingDate: `${student.academicYear - 1}`,
  tenthMedium: 'English',
  tenthMarks: `${Math.round(student.marksPercentage - 2)}%`,
  twelfthBoard: 'State Board',
  twelfthSchool: student.schoolType,
  twelfthPassingDate: `${student.academicYear - 1}`,
  twelfthMedium: 'English',
  twelfthMarks: `${student.hscMarks}%`,
  subjectMarks: student.recentSubjects.map((subject) => ({
    name: subject.name,
    mark: subject.grade,
  })),
  fatherQualification: 'Not provided',
  fatherOccupation: 'Not provided',
  fatherContact: student.guardianPhone,
  motherName: 'Not provided',
  motherQualification: 'Not provided',
  motherOccupation: 'Not provided',
  motherContact: 'Not provided',
  parentsOccupation: 'Not provided',
  boardOfStudy: 'State Board',
  mediumOfStudy: 'English',
  familyBackground: 'Not provided',
  agriculturalLandAvailability: student.agricultureBackground,
  cropsPlanted: 'Not provided',
  agriculturalLandLocality: 'Not provided',
  areaOfResidence: 'Urban',
  studiedTamilInXii: 'Yes',
});
